# Permalinks
permalink:           pretty

# Setup
title:               NDennett's blog
tagline:             This page under construction 
url:                 https://natdennett.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Nat Dennett 
  url:               https://linkedin.com/natdennettr
  email:             nathaniel.dennett@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/natdennett

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
